# Generated by Django 4.0.6 on 2022-07-10 08:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('lider', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Numero de Lider')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lider'),
        ),
    ]
