# Generated by Django 4.0.6 on 2022-07-20 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.TextField(max_length=50, verbose_name='Nombre/Empresa')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telefono')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Domicilio')),
                ('shipping', models.BooleanField(verbose_name='Entrega a domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('lider', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Numero de Lider')),
                ('doc_description', models.CharField(default='NOTA DE VENTA', max_length=250, verbose_name='Descripcion del documento')),
                ('doc_inks', models.CharField(choices=[('negra', 'NEGRA'), ('reflex', 'AZUL REFLEX'), ('rojo032', 'ROJO 032CV'), ('naranjaDirecto', 'NARANJA DIRECTO')], default='reflex', max_length=14)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now=True, verbose_name='Fecha ordenada')),
                ('expected_delivery_date', models.DateField(auto_now=True, verbose_name='Fecha esperada de Entrega')),
                ('quantity_ordered', models.PositiveIntegerField(default=0, verbose_name='Cantidad Solicitada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.lider')),
            ],
        ),
    ]
