# Generated by Django 4.1.3 on 2022-12-03 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50, verbose_name='Nombre/Empresa')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telefono')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Domicilio')),
                ('shipping', models.BooleanField(verbose_name='Entrega a domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('lider_id', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Numero de Lider')),
                ('doc_description', models.CharField(default='NOTA DE VENTA', max_length=250, verbose_name='Descripcion del formato')),
                ('doc_inks', models.CharField(choices=[('negra', 'NEGRA'), ('reflex', 'AZUL REFLEX'), ('rojo032', 'ROJO 032CV'), ('naranjaDirecto', 'NARANJA DIRECTO')], default='reflex', max_length=14)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre del Material')),
                ('quantity_ordered', models.FloatField(default=0, verbose_name='Cantidad')),
                ('unit_code', models.CharField(default='', max_length=5, verbose_name='Codigo Unidad')),
                ('unit_price', models.FloatField(default=0, verbose_name='Precio')),
                ('vat', models.CharField(choices=[('1.16', '16%'), ('1.08', '8%'), ('1', 'N/A')], default=1.08, max_length=4, verbose_name='Precio con IVA')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now=True, verbose_name='Fecha ordenada')),
                ('expected_delivery_date', models.DateField(auto_now=True, verbose_name='Fecha esperada de Entrega')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminado')),
                ('delivered', models.BooleanField(default=False, verbose_name='entregado')),
                ('paid', models.BooleanField(default=False, verbose_name='pagado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.material')),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.customer')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.lider')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.supplier'),
        ),
    ]
