# Generated by Django 4.1.3 on 2022-12-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lider',
            name='doc_inks',
        ),
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lider',
            name='doc_description',
            field=models.CharField(max_length=250, verbose_name='Descripcion del formato'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='RFC'),
        ),
    ]
