# Generated by Django 4.0.6 on 2022-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name_company',
            field=models.CharField(max_length=50, verbose_name='Nombre/Empresa'),
        ),
    ]
