# Generated by Django 4.1.3 on 2022-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_lider_doc_inks_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
