# Generated by Django 4.0.6 on 2022-07-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_name_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lider',
            old_name='lider',
            new_name='lider_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lider',
            new_name='lider_id',
        ),
    ]
