# Generated by Django 4.0.6 on 2022-08-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_lider_lider_lider_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nombre del Material')),
                ('quantity_ordered', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
    ]
