# Generated by Django 4.1.3 on 2022-12-12 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_unit_price_alter_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 7, 56, 454595), verbose_name='Fecha esperada de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='finished',
            field=models.BooleanField(verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
