# Generated by Django 4.1.3 on 2022-12-12 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_date_delivered_remove_order_date_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 42, 28, 319868), verbose_name='Fecha esperada de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
