# Generated by Django 4.1.3 on 2022-12-12 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Factura Asociada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 23, 21, 46, 797135), verbose_name='Fecha esperada de Entrega'),
        ),
    ]
