# Generated by Django 4.0.6 on 2022-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_materials_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Material'),
        ),
    ]
