# Generated by Django 4.1.3 on 2022-12-12 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_invoice_alter_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 23, 22, 2, 958330), verbose_name='Fecha esperada de Entrega'),
        ),
    ]
