# Generated by Django 4.0.6 on 2022-08-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_materials_size_materials_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='size',
            field=models.CharField(default='carta', max_length=20, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='vat',
            field=models.CharField(choices=[('1.16', '16%'), ('1.08', '8%'), ('1', 'N/A')], default=1.08, max_length=4),
        ),
    ]
