# Generated by Django 4.1.3 on 2022-12-14 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_expected_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 1, 49, 42, 856562), verbose_name='Fecha esperada de Entrega'),
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de quien ordena')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='Departamento')),
                ('contact', models.CharField(max_length=30, verbose_name='Telefono o Correo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
    ]
