# Generated by Django 4.1.3 on 2022-11-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_quotation_quotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
