# Generated by Django 4.1.3 on 2022-11-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderitem_customer_orderitem_quantity_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lider_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
    ]
