# Generated by Django 4.1.3 on 2022-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_complete_order_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='size',
        ),
        migrations.AddField(
            model_name='materials',
            name='unit_code',
            field=models.CharField(default='H87', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lider',
            name='doc_description',
            field=models.CharField(default='NOTA DE VENTA', max_length=250, verbose_name='Descripcion del formato'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
