# Generated by Django 4.1.3 on 2022-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_materials_quantity_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='unit_code',
            field=models.CharField(max_length=5, verbose_name='Codigo Unidad'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='vat',
            field=models.CharField(choices=[('1.16', '16%'), ('1.08', '8%'), ('1', 'N/A')], default=1.08, max_length=4, verbose_name='Precio con IVA'),
        ),
    ]
