# Generated by Django 4.1.3 on 2022-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_materials_unit_code_alter_materials_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='unit_price',
            field=models.FloatField(null=True, verbose_name='Precio'),
        ),
    ]
