# Generated by Django 4.1.3 on 2022-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_materials_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del Material'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='quantity_ordered',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='unit_code',
            field=models.CharField(default='', max_length=5, verbose_name='Codigo Unidad'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
