# Generated by Django 4.1.3 on 2022-11-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitem_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
